### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by saguadob** [saguadob/eiv-devsecops-course#1]
- [ ] Crear programa de curso compartido
- [ ] Lista de material a producir
- [ ] Crear lista de herramientas y recursos
- [ ] Crear tareas por cada Elemento

**Comment by lechip** [comment]
Cómo le ayudo entonces?
